name: GitHub Actions Demo
on:
  push:
    branches: main
  pull_request:
    branches: main
  schedule:
    - cron: "6 15 * * 0"
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: The Env to use
        required: true
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event }}"
      - run: echo "${{ github.ref }} and the repo is ${{ github.repository }}"
      - uses: actions/checkout@v3
      - run: tree
  Test:
    needs: Build
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - run: echo Testing...
  Test-Load:
    needs: Build
    runs-on: ubuntu-latest
    environment: LoadTest
    steps:
      - run: echo Load Testing...
      - run: sleep 15
      
  Deploy:
    needs: [Test, Test-Load]
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'AnEnvironment'
    steps:
      - run: echo "deploying..."
      - run: sleep 10
      - run: echo "deployed"
  
    
