name: GitHub Actions Demo
on:
  push:
    branches: main
  pull_request:
    branches: main
  schedule:
    - cron: "6 15 * * 0"
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event }}"
      - run: echo "${{ github.ref }} and the repo is ${{ github.repository }}"
      - uses: actions/checkout@v3
      - run: tree
    
